jina-ai/jina-hub

- encoders/numeric/RandomSparseEncoder/tests/test_randomsparseencoder.py
wrong name in test functions. it had gaussian encoder as name instead of sparse encoder
> refactor: wrong function name

- encoders/image/BigTransferEncoder/Dockerfile
- encoders/image/ImageKerasEncoder/Dockerfile
- encoders/image/ImageKerasEncoder/requirements.txt
Also, should we include `.dockerignore` for the build context?
> refactor(encoders): remove redundant docker instructions

- indexers/vector/ZarrIndexer/Dockerfile
- indexers/vector/ZarrIndexer/README.md
- indexers/vector/ZarrIndexer/__init__.py
- indexers/vector/ZarrIndexer/config.yml
- indexers/vector/ZarrIndexer/manifest.yml
- indexers/vector/ZarrIndexer/requirements.txt
- indexers/vector/ZarrIndexer/tests/test_zarrindexer.py
Indexer based on Zarr 
- Inherits `NumpyIndexer`
- `create_handler` & `add_handler` are based on opening a `Zarr Group`, inside which we write a `Zarr Array`
- `query_handler` reads the `Zarr Array`
- Avoid using `[:]` (which gives access to core np array), as that decreases the performance. 
- Memory usage is equivalent to `np.memmap`
Refs :
[Zarr Docs](https://zarr.readthedocs.io/en/stable/index.html)
[Zarr vs Python mmap](https://pythonspeed.com/articles/mmap-vs-zarr-hdf5/)
> Zarr Indexer

- encoders/numeric/CompressionVaeEncoder/Dockerfile
- encoders/numeric/CompressionVaeEncoder/README.md
- encoders/numeric/CompressionVaeEncoder/__init__.py
- encoders/numeric/CompressionVaeEncoder/config.yml
- encoders/numeric/CompressionVaeEncoder/manifest.yml
- encoders/numeric/CompressionVaeEncoder/requirements.txt
- encoders/numeric/CompressionVaeEncoder/tests/test_compressionvaeencoder.py
This pull request provides to the user an additional tool to encode data from a ndarray.
**CompressionVAE** is a fast, easy to use, dimensionality reduction tool based on the idea of [Variational Autoencoders](https://www.jeremyjordan.me/variational-autoencoders/). We can consider it an alternative to **t-SNE** and **UMAP**.
* **Pros**:
* **CompressionVAE** is faster than either **t-SNE** or **UMAP**.
* **CompressionVAE** learns a deterministic and reversible mapping from data to embedding space.
* It can be integrated into live systems that can process previously unseen examples without re-training.
* It can in principle scale to arbitrarily large datasets.
* **VAEs** have a very strong and well studied theoretical foundation.
* **Cons**:
* As almost any deep learning tool, it needs a …
> feat: add compression vae executor

- encoders/image/ImagePaddlehubEncoder/Dockerfile
- encoders/image/ImagePaddlehubEncoder/__init__.py
- encoders/image/ImagePaddlehubEncoder/manifest.yml
- encoders/image/ImagePaddlehubEncoder/tests/test_paddlehub.py
- encoders/video/VideoPaddleEncoder/Dockerfile
- encoders/video/VideoPaddleEncoder/__init__.py
- encoders/video/VideoPaddleEncoder/manifest.yml
- encoders/video/VideoPaddleEncoder/tests/test_videopaddleencoder.py
Since the addition of FluentdHandler, in the base executor there is a call to properly close the executor `logger`. So all the executors that override the close behavior should ensure that they call the parent close.
Besides this, PaddleHubEncoder was missing some dependencies to work properly
> feat: proper close

- rankers/BM25Ranker/manifest.yml
- rankers/BM25Ranker/tests/test_bm25ranker.py
- rankers/BiMatchRanker/__init__.py
- rankers/BiMatchRanker/manifest.yml
- rankers/BiMatchRanker/tests/test_bimatchranker.py
- rankers/LevenshteinRanker/manifest.yml
- rankers/LevenshteinRanker/tests/test_levenshteinranker.py
- rankers/MaxRanker/manifest.yml
- rankers/MaxRanker/tests/test_maxranker.py
- rankers/MinRanker/manifest.yml
- rankers/MinRanker/tests/test_minranker.py
- rankers/TfIdfRanker/manifest.yml
- rankers/TfIdfRanker/tests/test_tfidfranker.py
Ranker will work with latest jina version.
> fix: rankers are working with tree traversal

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/tests/test_transformertfencoder.py
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
This is a revert from some time ago. Alternative solution would be:
```
def __init__(self, *args, **kwargs):
super().init(self, *args, **kwargs)
Transformer(self, *args, **kwargs)
```
Multiclass inheritance is not always working as one would expect.
> fix: parameter overwrite enabled again

- indexers/vector/NmsLibIndexer/__init__.py
- indexers/vector/NmsLibIndexer/manifest.yml
- indexers/vector/NmsLibIndexer/tests/test_nmslibindexer.py
- indexers/vector/NmsLibIndexer/tests/yaml/nmslib-wrap.yml
NmsLib addBatch function assigns indexes to the vectors from 0 ... dataset_length per batch, therefore when doing `batching` need to take into account and return the ordered indexes to assign indexes to the vectors in the index.
Depends on https://github.com/jina-ai/jina/pull/1089
> test: add advanced tests to nmslib indexer

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/requirements.txt
- encoders/nlp/TransformerTFEncoder/tests/test_transformertfencoder.py
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/requirements.txt
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
I have updated the transformer encoders to be compatible with the v4.0 of the transformers library. 
Two main changes:
- instead of passing in an `ndarray` of strings, this is converted to a list - otherwise an error is raised in version 4.0.0 of transformers.
- I have replaced the use of the deprecated `pad_to_max_length` parameter with `padding` parameter. This has no effect whatsoever on behavior of the function.
All these changes do not in any way change the behavior for earlier versions of transformers.
I have also updated the requirements files slightly: for TF, I have replaced `==` with `>=` for tensorflow version - this is consistent with the requirements file for torch transformers. There were no breaking changes in later versions of tensorflow (I have tested locally on 2.3.0), …
> fix: update transformer encoders for v4 of transformers library

- indexers/vector/FaissIndexer/__init__.py
- indexers/vector/FaissIndexer/manifest.yml
- indexers/vector/FaissIndexer/tests/test_faissindexer.py
Fixes #1288 .
- Does not force compression level
- Allows having no loading data if not needed.
- Allow training data from uncompressed data if required
> fix: train_filepath can be none and loaded from binary

- rankers/BM25Ranker/__init__.py
- rankers/BM25Ranker/manifest.yml
- rankers/BM25Ranker/tests/test_bm25ranker.py
- rankers/BiMatchRanker/__init__.py
- rankers/BiMatchRanker/manifest.yml
- rankers/BiMatchRanker/tests/test_bimatchranker.py
- rankers/LevenshteinRanker/__init__.py
- rankers/LevenshteinRanker/manifest.yml
- rankers/LevenshteinRanker/tests/test_levenshteinranker.py
- rankers/MaxRanker/manifest.yml
- rankers/MaxRanker/tests/test_maxranker.py
- rankers/MinRanker/manifest.yml
- rankers/MinRanker/tests/test_minranker.py
- rankers/SimpleAggregateRanker/manifest.yml
- rankers/SimpleAggregateRanker/tests/test_aggregate_ranker.py
- rankers/TfIdfRanker/__init__.py
- rankers/TfIdfRanker/manifest.yml
- rankers/TfIdfRanker/tests/test_tfidfranker.py
This will adjust all Hub code to the hash to id change. We might need for another jina release before merging in order to make the core changes taking effect, right?
> refactor: hash to id for hub

- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
This adds 2 acceleration options to torch transformer: AMP and quantization. Here's a [notebook](https://colab.research.google.com/drive/1GEdRZXwr_vHIL9suzhHmE-jWezZMwv_R?usp=sharing) that demonstrates that these two acceleration options deliver a performance benefit - they can make the encoding up to 2x faster. Though this leads to loss of precision, so it should be used with care (a warning to this effect is added in the docstring).
> feat: torch transformer acceleration

- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
This moves model and tokenizer loading to post_init function.
> refactor: move model loading to post init for TorchTransformer

- crafters/image/ImageResizer/helper.py
- crafters/image/ImageResizer/manifest.yml
- crafters/image/ImageResizer/tests/test_imageresizer.py
it closes #165 
* added exception in the image resizer to work with 2d arrays or 3d arrays with shape (x, y, 1)
> fix: imageresizer gray

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/tests/test_transformertfencoder.py
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
This removes model/tokenizer saving from transformer encoders.
They are not needed as the models are simply used pretrained, no training (modification) is done.
> reformat: clean transformers

- encoders/image/BigTransferEncoder/README.md
- encoders/image/BigTransferEncoder/manifest.yml
`Hub executor documentation`:
- `BiT Encoder`
- Jinahub [jira-373](https://jinaai.atlassian.net/browse/JINAHUBV1-373)
> feat: add documentation for big transfer encoder

- encoders/image/ImageKerasEncoder/__init__.py
- encoders/image/ImageKerasEncoder/manifest.yml
- encoders/image/ImageKerasEncoder/tests/test_tfkeras.py
The `model_name` parameter never worked for the `ImageKerasEncoder`.
> fix: keras image encoder respects model name

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
This improves the transformer docstrings, better explaining the dimensionality of inputs (as prev. docstring seems to refer to image dimensions)
> docs: fix transformer docstrings

- rankers/BiMatchRanker/__init__.py
- rankers/BiMatchRanker/manifest.yml
Caused by https://github.com/jina-ai/jina/pull/1947
Several ways to solve this issue. Not sure which is the best. This issue caused the error of Tumblr-search.
1. See this PR
2. ` query_required_keys = ('length', )
match_required_keys = ('length', )
def __init__(self, d_miss: Optional[Union[int, float]] = None, *args, **kwargs):
super().__init__(self.query_required_keys, self. match_required_keys, *args, **kwargs)`
> fix: bimatchranker passing param

- indexers/vector/FaissIndexer/__init__.py
- indexers/vector/FaissIndexer/manifest.yml
- indexers/vector/FaissIndexer/tests/test_faissindexer.py
Hi there,
in this fix results of query in a Faiss index will be always as top-k vector with smallest metric, so in ascending order.
The problem in this issue was specific on inner_product that returns similarity and not distances.
> fix: faiss indexer inner_product returns sim and not distance (#3524)

- segmenters/nlp/Sentencizer/__init__.py
- segmenters/nlp/Sentencizer/manifest.yml
- segmenters/nlp/Sentencizer/tests/test_sentencizer.py
Address issue https://github.com/jina-ai/jina-hub/issues/5141
Background:
Function `segment` of `Sentencizer` currently doesn't handle text in chinese and many other languages, because the filter uses string.printable, which is limited to english characters.
In this PR:
* Add another input argument to segment indicating which language the input text is, set default value as "en".
* Change segment to only apply filter on english texts.
* Add and update multiple tests for feature validation.
> feat: fix sentencizer on other languages

- segmenters/nlp/JiebaSegmenter/__init__.py
- segmenters/nlp/JiebaSegmenter/manifest.yml
- segmenters/nlp/JiebaSegmenter/tests/dict.txt
- segmenters/nlp/JiebaSegmenter/tests/test_jiebasegmenter.py
This PR adds a new option to the `JiebaSegmenter` by exposing an existing feature in the Jieba library:
Allow the user to extend the default dict by a custom dict of their choice. The dict needs to be specified as a path in the `user_dict_file` parameter. The format of the dict is specified in the [Jieba repository](https://github.com/fxsjy/jieba#load-dictionary)
This feature was requested in this [issue](https://github.com/jina-ai/jina-hub/issues/5142), which did not specify exactly which features to expose. 
Potentially one could also expose the functionality to [modify the existing dict](https://github.com/fxsjy/jieba#modify-dictionary). That seemed a bit too cumbersome for the user to me though.
The custom dict feature assumes that the dictionary file is accessible locally. If that …
> feat(segmenter): add user dict to JiebaSegmenter

- rankers/BiMatchRanker/__init__.py
- rankers/BiMatchRanker/manifest.yml
- rankers/BiMatchRanker/tests/test_bimatchranker.py
`_groups_best = np.stack([np.sort(gg, order=col)[0] for gg in _groups])`
should sort by 'score' to get the best, this won't have effect if we use default d_miss value since it has a large value.
> fix(bimatch): fix group by order

- crafters/numeric/ArrayStringReader/manifest.yml
We released a new jina version that catches errors and fails with hubapi related exceptions. This is a PR that I want to merge to verify the hubapi invocations during CD.
> chore: version bump to test issues with hub database

- encoders/nlp/TransformerTorchEncoder/README.md
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/requirements.txt
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
Enables the usage of the huggingface API instead of calling a model locally. To enable it, just add an API token to the encoder. The model will not be loaded locally at all.
```
!TransformerTorchEncoder
with:
pooling_strategy: auto
pretrained_model_name_or_path: distilbert-base-cased
max_length: 192
api_token: ${{JINA_HUGGINGFACE_API_TOKEN}}
```
> feat: added huggingface api calls

- encoders/nlp/TFIDFTextEncoder/__init__.py
- encoders/nlp/TFIDFTextEncoder/manifest.yml
- encoders/nlp/TFIDFTextEncoder/tests/test_tfidftextencoder.py
The encoder could 'silently break' if the path to the trained vectorizer did not exist. This PR fixes this.
> fix: check path to vectorizer exists

- indexers/vector/PysparnnIndexer/__init__.py
- indexers/vector/PysparnnIndexer/manifest.yml
Pysparnn does not behave as expected when there distances are strings [as shown here.](https://github.com/facebookresearch/pysparnn/issues/35) This PR fixes the issue casting them into floats and sorting the results.
> fix: sorting properly casting strings to floats

- indexers/keyvalue/MongoDBIndexer/__init__.py
- indexers/keyvalue/MongoDBIndexer/manifest.yml
- indexers/keyvalue/MongoDBIndexer/tests/test_mongodbindexer.py
This PR allows query to work on `keys:Iterable[str]`
> feat: add batching query capability to mongodbindexer
