- hub/executors/encoders/nlp/transformers-pytorch/manifest.yml
> fix: update to the latest jina

- .github/workflows/cd.yml
Fixed ci dependencies after `--update-strategy` grid update.
> ci: fix dependencies

- hub/executors/encoders/image/torchvision-mobilenet_v2/manifest.yml
> feat: add the version info

- hub/executors/encoders/image/torchvision-mobilenet_v2/manifest.yml
> Revert "feat: add the version info"

- hub/executors/encoders/image/torchvision-mobilenet_v2/manifest.yml
- hub/executors/encoders/nlp/transformers-hitscir/manifest.yml
> feat: add the update field

- .github/workflows/ci.yml
- hub/executors/indexers/vector/faiss/Dockerfile
- hub/executors/indexers/vector/faiss/README.md
- hub/executors/indexers/vector/faiss/faiss.yml
- hub/executors/indexers/vector/faiss/manifest.yml
> add the docker image for faiss indexer

- hub/executors/encoders/image/torchvision-mobilenet_v2/manifest.yml
add the missing keywords for the images.
> chore: add the missing keywords

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/issue-ref.yml
> fix: fix the cicd process

- builder/app.py
- builder/manifest.yml
- builder/osi-approved.yml
- builder/platforms.yml
- builder/requirements.txt
add missing files for [PR-92](https://github.com/jina-ai/jina-hub/pull/92)
> fix: add missing files for reverting cicd

- hub/executors/encoders/image/facenet/Dockerfile
- hub/executors/encoders/image/facenet/FaceNetEncoder.py
- hub/executors/encoders/image/facenet/encode.yml
- hub/executors/encoders/image/facenet/install.sh
- hub/executors/encoders/image/facenet/manifest.yml
- hub/executors/encoders/image/facenet/requirements.txt
FaceNet Encoder for returning vector embeddings for each face.
Based on FaceNet by : Florian Schroff, Dmitry Kalenichenko, James Philbin ( PyTorch implementation)
> feat(encoder): add facenet encoder

- builder/app.py
- hub/executors/indexers/vector/faiss/Dockerfile
- hub/executors/indexers/vector/faiss/README.md
- hub/executors/indexers/vector/faiss/faiss.yml
> fix: fix the faiss image

- rankers/MaxRanker/Dockerfile
- rankers/MaxRanker/README.md
- rankers/MaxRanker/__init__.py
- rankers/MaxRanker/config.yml
- rankers/MaxRanker/manifest.yml
- rankers/MaxRanker/requirements.txt
- rankers/MaxRanker/tests/test_maxranker.py
> refactor(rankers): migrate MaxRanker

- rankers/MinRanker/Dockerfile
- rankers/MinRanker/README.md
- rankers/MinRanker/__init__.py
- rankers/MinRanker/config.yml
- rankers/MinRanker/manifest.yml
- rankers/MinRanker/requirements.txt
- rankers/MinRanker/tests/test_minranker.py
> refactor(MinRanker): migrate

- encoders/nlp/OneHotTextEncoder/Dockerfile
- encoders/nlp/OneHotTextEncoder/README.md
- encoders/nlp/OneHotTextEncoder/__init__.py
- encoders/nlp/OneHotTextEncoder/config.yml
- encoders/nlp/OneHotTextEncoder/manifest.yml
- encoders/nlp/OneHotTextEncoder/tests/test_onehottextencoder.py
> refactor(encoder): migrate OneHotTextEncoder

- indexers/vector/NmsLibIndexer/Dockerfile
- indexers/vector/SptagIndexer/Dockerfile
- indexers/vector/SptagIndexer/__init__.py
- indexers/vector/SptagIndexer/tests/test_sptagindexer.py
- indexers/vector/SptagIndexer/tests/yaml/sptag-wrap.yml
This is one step to fix the docker build, but test is still failing because the code does not do what it should
> Fix sptagindexer

- indexers/vector/NmsLibIndexer/Dockerfile
> fix: fix nmslibindexer build image

- encoders/image/CustomImageTorchEncoder/tests/test_customimagetorchencoder.py
Load config not working because no default params for model_path and layer_name
> fix: test failing because no default parameter

- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
Test was failing because did not store without touch
> fix: touch before save in test

- encoders/numeric/RandomGaussianEncoder/tests/test_randomgaussianencoder.py
- encoders/numeric/RandomSparseEncoder/Dockerfile
- encoders/numeric/RandomSparseEncoder/README.md
- encoders/numeric/RandomSparseEncoder/__init__.py
- encoders/numeric/RandomSparseEncoder/config.yml
- encoders/numeric/RandomSparseEncoder/manifest.yml
- encoders/numeric/RandomSparseEncoder/requirements.txt
- encoders/numeric/RandomSparseEncoder/tests/test_randomsparseencoder.py
> refactor: migrate random sparse encoder[149]

- encoders/video/VideoPaddleEncoder/Dockerfile
- encoders/video/VideoPaddleEncoder/__init__.py
- encoders/video/VideoPaddleEncoder/manifest.yml
- encoders/video/VideoPaddleEncoder/requirements.txt
1. added related pip requirements
2. put `or` values to default init ones
Resolved: #170
> refactor: migrate VideoPaddleEncoder

- encoders/nlp/LaserEncoder/Dockerfile
- encoders/nlp/LaserEncoder/README.md
- encoders/nlp/LaserEncoder/__init__.py
- encoders/nlp/LaserEncoder/config.yml
- encoders/nlp/LaserEncoder/manifest.yml
- encoders/nlp/LaserEncoder/requirements.txt
- encoders/nlp/LaserEncoder/tests/test_laserencoder.py
> feat: add laser encoder

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/requirements.txt
- encoders/nlp/TransformerTFEncoder/tests/test_transformertfencoder.py
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/requirements.txt
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
This fixes `CLS` vector issue mentioned in #192 
Debugging details in this [notebook](https://colab.research.google.com/drive/1DEsqUIG2doF0wIy8Hmr4HvhXKXalu5iu?usp=sharing).
> Fix encoder nlp transformer 192

- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
> chore: changed misspelling

- rankers/LevenshteinRanker/Dockerfile
- rankers/LevenshteinRanker/README.md
- rankers/LevenshteinRanker/__init__.py
- rankers/LevenshteinRanker/config.yml
- rankers/LevenshteinRanker/manifest.yml
- rankers/LevenshteinRanker/requirements.txt
- rankers/LevenshteinRanker/tests/test_levenshteinranker.py
Adding a Levenshtein distance ranker to the hub. That might not be to useful in practice, but rather gives an example how to use the `Match2DocRanker`.
> Feat levenshtein distance ranker

- README.md
> fix: added quotation mark

- encoders/image/ImageTorchEncoder/__init__.py
- encoders/image/ImageTorchEncoder/manifest.yml
> fix: fix model_name default parameter for ImageTorchEncoder

- indexers/vector/FaissIndexer/__init__.py
- indexers/vector/FaissIndexer/manifest.yml
Make faiss be built profiting of the `batch_size` memmap optimizations
> feat: add batching to build_advanced_index

- encoders/image/ImageKerasEncoder/config.yml
- encoders/image/ImageKerasEncoder/manifest.yml
Adapting `ImageKerasEncoder` for the new tree traversal already used in the encoders.
> feat: keras uses tree traversal

- rankers/BM25Ranker/__init__.py
- rankers/BiMatchRanker/__init__.py
- rankers/LevenshteinRanker/__init__.py
- rankers/MaxRanker/__init__.py
- rankers/MinRanker/__init__.py
- rankers/TfIdfRanker/__init__.py
Fixes the float int conversion error that happened for the new hashes. See https://github.com/jina-ai/jina/pull/1034
> fix: fixed the error appearing due to int float conversion

- crafters/image/ImageNormalizer/__init__.py
- crafters/image/ImageNormalizer/manifest.yml
- crafters/image/ImageNormalizer/tests/test_imagenormalizer.py
- crafters/image/ImageResizer/__init__.py
- crafters/image/ImageResizer/manifest.yml
_resize_short accepts only tuple. Fixes jina-ai/examples#235
> fix: added tuple support

- indexers/vector/ZarrIndexer/manifest.yml
- indexers/vector/ZarrIndexer/tests/test_zarrindexer.py
> test: add advanced tests to zarr indexer

- indexers/vector/NGTIndexer/__init__.py
- indexers/vector/NGTIndexer/manifest.yml
- indexers/vector/NGTIndexer/tests/test_ngtindexer.py
> test: add advanced tests to ngt indexer

- indexers/vector/ScannIndexer/__init__.py
- indexers/vector/ScannIndexer/manifest.yml
- indexers/vector/ScannIndexer/tests/test_scannindexer.py
> test: add advanced tests to scann indexer

- indexers/vector/AnnoyIndexer/manifest.yml
- indexers/vector/AnnoyIndexer/tests/test_annoyindexer.py
- indexers/vector/AnnoyIndexer/tests/yaml/annoy-wrap.yml
> test: add advanced tests to annoy indexer

- indexers/vector/FaissIndexer/Dockerfile
- indexers/vector/FaissIndexer/manifest.yml
- indexers/vector/FaissIndexer/requirements.txt
- indexers/vector/FaissIndexer/tests/test_faissindexer.py
> test: add advanced tests to faiss indexer

- indexers/vector/SptagIndexer/__init__.py
- indexers/vector/SptagIndexer/manifest.yml
- indexers/vector/SptagIndexer/tests/test_sptagindexer.py
- indexers/vector/SptagIndexer/tests/yaml/sptag-wrap.yml
There is a test that I skipped because it fails but I think is because we failed to find the proper configuration of parameters to make it work. SPTAG has not really good documentation
> test: sptag advanced indexer testing

- indexers/vector/NmsLibIndexer/__init__.py
- indexers/vector/NmsLibIndexer/manifest.yml
- indexers/vector/NmsLibIndexer/tests/test_nmslibindexer.py
- indexers/vector/NmsLibIndexer/tests/yaml/nmslib-wrap.yml
Since I realized https://github.com/jina-ai/jina/issues/1091 is feasilbe, I remembered that here there is a dict parameter that should be exposed
> feat: expose index params

- evaluators/text/EditDistanceEvaluator/Dockerfile
- evaluators/text/EditDistanceEvaluator/README.md
- evaluators/text/EditDistanceEvaluator/__init__.py
- evaluators/text/EditDistanceEvaluator/config.yml
- evaluators/text/EditDistanceEvaluator/manifest.yml
- evaluators/text/EditDistanceEvaluator/requirements.txt
- evaluators/text/EditDistanceEvaluator/tests/test_editdistanceevaluator.py
> feat: add edit distance evaluator

- README.md
> docs: add hint that this requires docker

- .github/workflows/ci.yml
- .github/workflows/update-test.yml
+ Add new Hub Updater action
+ Make `ci.yml` hub builder also push images
> ci: add updater and make builder push by default

- indexers/keyvalue/MongoDBIndexer/__init__.py
- indexers/keyvalue/MongoDBIndexer/manifest.yml
- indexers/keyvalue/MongoDBIndexer/mongodbhandler.py
- indexers/keyvalue/MongoDBIndexer/tests/test_mongodbindexer.py
Add update and delete to MongoDBIndexer
> feat: add update and delete to mongodbindexer

- indexers/keyvalue/RedisDBIndexer/Dockerfile
- indexers/keyvalue/RedisDBIndexer/__init__.py
- indexers/keyvalue/RedisDBIndexer/manifest.yml
- indexers/keyvalue/RedisDBIndexer/requirements.txt
- indexers/keyvalue/RedisDBIndexer/tests/test_redisdbindexer.py
- indexers/keyvalue/RedisDBIndexer/tests/yaml/test-redis.yml
Related ticket:
https://jinaai.atlassian.net/browse/JINACORE-483
Adding update and delete operations for RedisDBIndexer.
> Feat redis update and delete

- indexers/keyvalue/LevelDBIndexer/Dockerfile
- indexers/keyvalue/LevelDBIndexer/__init__.py
- indexers/keyvalue/LevelDBIndexer/manifest.yml
- indexers/keyvalue/LevelDBIndexer/requirements.txt
- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
Related ticket:
https://jinaai.atlassian.net/browse/JINACORE-483
Adding update and delete operations for LevelDBIndexer.
> feat(leveldbindexer): update and delete

- encoders/nlp/TransformerTFEncoder/__init__.py
- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/tests/test_transformertfencoder.py
- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
Adds `layer_index` param to both transformer encoders. Closes #1284
> feat: add layer_index param to transformer encoders

- indexers/vector/FaissIndexer/__init__.py
- indexers/vector/FaissIndexer/manifest.yml
- indexers/vector/FaissIndexer/tests/test_faissindexer.py
This requires https://github.com/jina-ai/jina/pull/1415
> feat: add update / delete to faiss indexer

- indexers/vector/AnnoyIndexer/__init__.py
- indexers/vector/AnnoyIndexer/manifest.yml
- indexers/vector/AnnoyIndexer/tests/test_annoyindexer.py
Requires https://github.com/jina-ai/jina/pull/1415
> feat: update/delete for annoy indexer

- .github/workflows/update-test.yml
Add comparison level for when new Jina releases should be tested.
> ci: specify comparison level

- encoders/nlp/TextPaddlehubEncoder/manifest.yml
- encoders/nlp/TextPaddlehubEncoder/requirements.txt
> fix: fix versions TextPaddlehubEncoder

- encoders/nlp/TransformerTorchEncoder/__init__.py
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/requirements.txt
> fix: fix torch encoder

- evaluators/rank/ReciprocalRankEvaluator/__init__.py
- evaluators/rank/ReciprocalRankEvaluator/manifest.yml
- evaluators/rank/ReciprocalRankEvaluator/tests/test_reciprocalrankevaluator.py
> fix: fix reciprocal rank evaluator

- crafters/nlp/TikaExtractor/__init__.py
- crafters/nlp/TikaExtractor/manifest.yml
- crafters/nlp/TikaExtractor/requirements.txt
> fix: fix tika extractor

- encoders/nlp/TextPaddlehubEncoder/Dockerfile
- encoders/nlp/TextPaddlehubEncoder/manifest.yml
> fix: fix text paddle hub encoder

- encoders/nlp/TransformerTFEncoder/manifest.yml
- encoders/nlp/TransformerTFEncoder/requirements.txt
> fix: tf encoder remove jina from requirements

- rankers/BM25Ranker/__init__.py
- rankers/BM25Ranker/manifest.yml
> fix: fix the required_keys

- encoders/image/CustomImageTorchEncoder/Dockerfile
- encoders/image/CustomImageTorchEncoder/__init__.py
- encoders/image/CustomImageTorchEncoder/manifest.yml
- encoders/image/CustomImageTorchEncoder/tests/test_customimagetorchencoder.py
> fix: set default model for custom image torch encoder

- encoders/nlp/TransformerTFEncoder/Dockerfile
- encoders/nlp/TransformerTFEncoder/manifest.yml
properly cleans transformer test artifacts, should reduce the image size by a few GB :)
> fix: clean tf transformer encoder artifacts

- encoders/image/CustomImageTorchEncoder/__init__.py
- encoders/image/CustomImageTorchEncoder/manifest.yml
- indexers/keyvalue/LevelDBIndexer/manifest.yml
- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
- indexers/keyvalue/RedisDBIndexer/manifest.yml
- indexers/keyvalue/RedisDBIndexer/tests/test_redisdbindexer.py
- indexers/vector/MilvusIndexer/milvusdbhandler.py
- rankers/SimpleAggregateRanker/manifest.yml
- rankers/SimpleAggregateRanker/tests/test_aggregate_ranker.py
> refactor: shadowing built ins

- encoders/image/TirgImageEncoder/Dockerfile
- encoders/image/TirgImageEncoder/manifest.yml
- encoders/multimodal/TirgMultimodalEncoder/Dockerfile
- encoders/multimodal/TirgMultimodalEncoder/__init__.py
- encoders/multimodal/TirgMultimodalEncoder/manifest.yml
Update positional modality for the multimodal encoder, and update text model url.
> fix: update multimodal encoder

- indexers/keyvalue/RedisDBIndexer/Dockerfile
- indexers/keyvalue/RedisDBIndexer/__init__.py
- indexers/keyvalue/RedisDBIndexer/manifest.yml
- indexers/keyvalue/RedisDBIndexer/tests/test_redisdbindexer.py
Required by https://github.com/jina-ai/cloud-ops/pull/74
> fix: redis indexer

- segmenters/nlp/PDFExtractorSegmenter/manifest.yml
- segmenters/nlp/PDFExtractorSegmenter/tests/README.md
- segmenters/nlp/PDFExtractorSegmenter/tests/test_pdf_flow.py
Closes #https://github.com/jina-ai/jina-hub/issues/3032
> fix: PDFExtractorSegmenter on done

- crafters/image/ImageReader/manifest.yml
- crafters/image/ImageReader/tests/test_imagereader.py
> fix: tests in imagereader

- encoders/nlp/TransformerTorchEncoder/Dockerfile
- encoders/nlp/TransformerTorchEncoder/gpu.Dockerfile
- encoders/nlp/TransformerTorchEncoder/manifest.yml
- encoders/nlp/TransformerTorchEncoder/tests/test_transformertorchencoder.py
fix timeout ready transformertorchencoder
> fix timeout ready transformertorchencoder

- README.md
Feature: Add a link to the Jina Hub
> feat: add link to hub.jina.ai

- crafters/audio/AudioNormalizer/README.md
- crafters/audio/AudioNormalizer/manifest.yml
This PR is for [JINAHUBV1-359](https://jinaai.atlassian.net/browse/JINAHUBV1-360?atlOrigin=eyJpIjoiOWYxZjhkMWE4ZjhkNGQ2NWIwOTJmODg2MGY5MGFiYWQiLCJwIjoiaiJ9).
In the README:
> docs: add documentation for AudioNormalizer

- crafters/audio/AudioReader/README.md
- crafters/audio/AudioReader/manifest.yml
This PR is for [JINAHUBV1-359](https://jinaai.atlassian.net/browse/JINAHUBV1-359?atlOrigin=eyJpIjoiYTJhY2M5ZWEwZjMwNGViNTk0YjUxMDZhMmRlNmU4MjAiLCJwIjoiaiJ9).
In the README:
> docs: add documentation for AudioReader

- crafters/image/ImageReader/README.md
- crafters/image/ImageReader/manifest.yml
This PR is for [JINAHUBV1-359](https://jinaai.atlassian.net/browse/JINAHUBV1-361?atlOrigin=eyJpIjoiN2FmYjM2ZTFhOTMxNDcxMGI4YzA2NmVkOWM3OTFkYjMiLCJwIjoiaiJ9).
In the README:
> docs: add documentation for ImageReader

- encoders/image/TirgImageEncoder/README.md
- encoders/image/TirgImageEncoder/__init__.py
- encoders/image/TirgImageEncoder/img_text_composition_models.py
- encoders/image/TirgImageEncoder/manifest.yml
- encoders/image/TirgImageEncoder/tests/test_tirg_image_encoder.py
- encoders/image/TirgImageEncoder/text_model.py
- encoders/image/TirgImageEncoder/torch_functions.py
Update docstring for `TirgImageEncoder`.
> docs: add docstring for tirg image encoder

- segmenters/nlp/Sentencizer/README.md
- segmenters/nlp/Sentencizer/manifest.yml
This pr is for JINAHUBV1-370. 
Let me know what else should we add to the content. 😄 
In the README:
> docs(sentencizer): update readme and manifest

- segmenters/nlp/DeepSegmenter/README.md
- segmenters/nlp/DeepSegmenter/manifest.yml
This pr is for JINAHUBV1-371. 
Let me know what else should we add to the content. 😄 
In the README:
> docs(deepsegmenter): update readme and manifest

- encoders/image/VSEImageEncoder/README.md
- encoders/image/VSEImageEncoder/__init__.py
- encoders/image/VSEImageEncoder/manifest.yml
- encoders/image/VSEImageEncoder/tests/test_vseimageencoder.py
Add docstring for VSE++ image encoder.
> docs: add docstring for vse image encoder

- encoders/image/ImageKerasEncoder/README.md
- encoders/image/ImageKerasEncoder/__init__.py
- encoders/image/ImageKerasEncoder/manifest.yml
- encoders/image/ImageKerasEncoder/tests/test_tfkeras.py
> feat: add docs for keras image encoder

- rankers/SimpleAggregateRanker/__init__.py
- rankers/SimpleAggregateRanker/manifest.yml
Need to wait https://github.com/jina-ai/jina-hub/pull/4148
> fix: add deprecated param for simpleaggregateranker

- segmenters/nlp/SpacySentencizer/Dockerfile
- segmenters/nlp/SpacySentencizer/README.md
- segmenters/nlp/SpacySentencizer/__init__.py
- segmenters/nlp/SpacySentencizer/config.yml
- segmenters/nlp/SpacySentencizer/manifest.yml
- segmenters/nlp/SpacySentencizer/requirements.txt
- segmenters/nlp/SpacySentencizer/tests/test_sentencizer.py
- segmenters/nlp/SpacySentencizer/tests/test_spacysentencizer.py
In this implementation, the splitting technique is divided into two different approaches:
1. Default Segmenter: Utilizes dependency parsing to determine the rule for splitting the text. For more info please refer to https://spacy.io/api/sentencizer.
2. Machine Learning-based Segmenter: Utilizes SentenceRecognizer model trained on a dedicated data created for sentence segmentation. For more info please refer to https://spacy.io/api/sentencerecognizer.
> feat(segmenter): add spacy sentencizer

- evaluators/embedding/L1NormEvaluator/README.md
- evaluators/embedding/L1NormEvaluator/__init__.py
- evaluators/embedding/L1NormEvaluator/manifest.yml
- evaluators/embedding/L1NormEvaluator/tests/test_l1norm.py
Docstring for `l1 norm evaluator`
> fix: docstring for l1 norm evaluator

- README.md
Problem definition:
The file structure should includes `config.yml`.
> fix: add config.yml in hub structure

- encoders/image/ImageTorchEncoder/README.md
- encoders/image/ImageTorchEncoder/__init__.py
- encoders/image/ImageTorchEncoder/manifest.yml
- encoders/image/ImageTorchEncoder/tests/test_imagetorchencoder.py
Docstring for `imagetorch` encoder
> fix: docstring for imagetorch encoder

- rankers/LevenshteinRanker/README.md
- rankers/LevenshteinRanker/__init__.py
- rankers/LevenshteinRanker/manifest.yml
- rankers/LevenshteinRanker/tests/test_levenshteinranker.py
Adds documentation for `Levenshtein ranker`
> feat: doc update for levenshtein ranker

- evaluators/text/BleuEvaluator/README.md
- evaluators/text/BleuEvaluator/__init__.py
- evaluators/text/BleuEvaluator/manifest.yml
- evaluators/text/BleuEvaluator/tests/test_bleuevaluator.py
> feat: add doc for bleu evaluator

- crafters/image/ImageResizer/README.md
- crafters/image/ImageResizer/manifest.yml
- crafters/image/ImageResizer/tests/test_imageresizer.py
Doc for `imageresizer` crafter
> feat: doc for image resizer crafter

- indexers/keyvalue/LevelDBIndexer/README.md
- indexers/keyvalue/LevelDBIndexer/__init__.py
- indexers/keyvalue/LevelDBIndexer/manifest.yml
- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
Doc for `LevelDB` indexer usage.
> feat: leveldb indexer usage doc

- crafters/audio/AudioMonophoner/README.md
- crafters/audio/AudioMonophoner/__init__.py
- crafters/audio/AudioMonophoner/manifest.yml
- crafters/audio/AudioMonophoner/tests/test_audiomonophoner.py
Doc for `audiomonophoner` crafter
> feat: doc for audiomonophoner crafter

- crafters/image/AlbumentationsCrafter/README.md
- crafters/image/AlbumentationsCrafter/__init__.py
- crafters/image/AlbumentationsCrafter/manifest.yml
- crafters/image/AlbumentationsCrafter/tests/test_albumentationscrafter.py
Doc for `albumentation` crafter
> feat: doc for albumentation crafter

- indexers/vector/AnnoyIndexer/README.md
- indexers/vector/AnnoyIndexer/__init__.py
- indexers/vector/AnnoyIndexer/manifest.yml
- indexers/vector/AnnoyIndexer/tests/test_annoyindexer.py
- Add usage for `AnnoyIndexer`
> feat: increase verbosity for annoy indexer

- indexers/vector/NGTIndexer/README.md
- indexers/vector/NGTIndexer/__init__.py
- indexers/vector/NGTIndexer/manifest.yml
- indexers/vector/NGTIndexer/tests/test_ngtindexer.py
>  feat: increase verbosity for ngt indexer

- indexers/vector/NmsLibIndexer/README.md
- indexers/vector/NmsLibIndexer/__init__.py
- indexers/vector/NmsLibIndexer/manifest.yml
- indexers/vector/NmsLibIndexer/tests/test_nmslibindexer.py
Add usage for `nmslib` indexer
> feat: increase verbosity for nms indexer

- indexers/vector/FaissIndexer/README.md
- indexers/vector/FaissIndexer/__init__.py
- indexers/vector/FaissIndexer/manifest.yml
- indexers/vector/FaissIndexer/tests/test_faissindexer.py
- Usage doc for `Faiss Indexer`
> feat: increase verbosity for faiss indexer

- .github/workflows/ci.yml
> fix: add classifiers folder

- segmenters/nlp/NLTKSentencizer/Dockerfile
- segmenters/nlp/NLTKSentencizer/README.md
- segmenters/nlp/NLTKSentencizer/__init__.py
- segmenters/nlp/NLTKSentencizer/config.yml
- segmenters/nlp/NLTKSentencizer/manifest.yml
- segmenters/nlp/NLTKSentencizer/requirements.txt
- segmenters/nlp/NLTKSentencizer/tests/test_nltksentencizer.py
My implementation for Sentencizer with NLTK
> Feat nltk sentencizer 5790

- indexers/keyvalue/LevelDBIndexer/__init__.py
- indexers/keyvalue/LevelDBIndexer/manifest.yml
- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
it is not needed to remove before adding.
> Refactor leveldbindexer update

- encoders/numeric/UMAPEncoder/README.md
- encoders/numeric/UMAPEncoder/manifest.yml
This PR fixes some markdown issues in the README doc for `UMAPEncoder`.
> docs(umapencoder): fix code snippet formatting

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Context: https://jinaai.slack.com/archives/C0183GCN8AK/p1616570713024500
> ci: change to pull_request_target to allow community pr

- rankers/BiMatchRanker/__init__.py
- rankers/BiMatchRanker/manifest.yml
- rankers/BiMatchRanker/tests/test_bimatchranker.py
related PR: https://github.com/jina-ai/jina/pull/2234
> fix(ranker): change length to siblings

- .github/workflows/merge-dependabot.yml
GitHub script as per:
https://github.com/marketplace/actions/dependabot-auto-merge
for auto-merging dependabot PRs labeled with `dependencies`, `github.actor` is dependabot and PR has `bump jinaai/jina` in the name.
> feat: github workflow for dependabot pr auto merge

- crafters/image/ImageNormalizer/__init__.py
- crafters/image/ImageNormalizer/manifest.yml
- crafters/image/ImageNormalizer/tests/test_imagenormalizer.py
Background: 
https://github.com/jina-ai/jina-hub/pull/7565
The previous code might doesn't work as expected.
> feat: enable changing channel axis

- classifiers/image/CLIPZeroShotClassifier/README.md
- classifiers/image/CLIPZeroShotClassifier/__init__.py
- classifiers/nlp/TransformersTorchSeqClassifier/README.md
- classifiers/nlp/TransformersTorchSeqClassifier/__init__.py
- classifiers/nlp/ZeroShotTFClassifier/__init__.py
replace all `data` in `classifiers` to `content`.
> feat: update argument in classifiers

- .github/workflows/ci.yml
- .github/workflows/cla.yml
- .github/workflows/merge-dependabot.yml
> fix: fix the tokens

- indexers/keyvalue/LevelDBIndexer/__init__.py
- indexers/keyvalue/LevelDBIndexer/manifest.yml
- indexers/keyvalue/LevelDBIndexer/tests/test_leveldbindexer.py
This PR should add query working on batches.
> feat: query on batches leveldbindexer

- indexers/dbms/BinaryPbIndexer/__init__.py
- indexers/dbms/BinaryPbIndexer/tests/test_indexer.py
- indexers/dump.py
- indexers/keyvalue/FileQueryIndexer/__init__.py
- indexers/vector/NumpyIndexer/__init__.py
This makes indexers runnable. added the `dump` code.
> feat: added dump code to hub

- .github/dependabot.yml
chore: ignore 2.0 in dependabot for the time being
> chore: ignore 2.0 in dependabot

- crafters/image/ImageNormalizer/__init__.py
- crafters/image/ImageNormalizer/manifest.yml
related PR:https://github.com/jina-ai/jina/pull/2452
> fix: fix move axis

- crafters/nlp/TikaExtractor/requirements.txt
- encoders/image/VSEImageEncoder/requirements.txt
- encoders/nlp/VSETextEncoder/requirements.txt
- indexers/dbms/PostgreSQLIndexer/requirements.txt
- indexers/keyvalue/MongoDBIndexer/requirements.txt
> fix: use git for pip installation
